### ISSUE TITLE
Possible type-o in ansi.py?

### ISSUE THREAD

**Issue by swhcz** [lskbr/colorconsole#4]
Hi there,

first off excellent project, like it very much and definitely helps keeping my script's output tidy!

When stumbling through the code (version 0.7.2) I ended up in ansi.py, in reset_colors(), line 190.

Here it says:
```
def reset_colors(self):
    self.default_background()
    self.default_foreground
    self.reset()
```

shouldn't there be a "()" after "self.default_foreground" ?

Thanks!
Sebastian.

**Comment by lskbr** [comment]
Nice catch! I'm planning to do some more testing and wrap up version 1.0.

Thanx for reporting this glitch!

Nilo Menezes

**Comment by swhcz** [comment]
You're welcome!
Sebastian.
