### ISSUE TITLE
Error on windows python

### ISSUE THREAD

**Issue by not-sekiun** [lskbr/colorconsole#5]
I pip installed colorconsole using python 2.7.13 and managed to succesfully import it. However upon testing it I get the error, ```ctypes.ArgumentError: argument 4: <type 'exceptions.TypeError'>: wrong type```.
The full traceback is
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\colorconsole\terminal.py", line 69, in test
    t.clear()
  File "C:\Python27\lib\site-packages\colorconsole\win.py", line 170, in clear
    sx, rp, byref(wr))
ctypes.ArgumentError: argument 4: <type 'exceptions.TypeError'>: wrong type
```
How can I prevent this?

**Comment by ghost** [comment]
I encounted this issue as well!. 

After a series of frustrating google searches, I found something that might help at the link below:

https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/prompt_toolkit/output/win32.py (Look at _coord_byval routine). 

Editing win.py accordingly helps.

**Comment by lskbr** [comment]
I updated the library after a long winter. Python 2.7 is not anymore supported. 32 bit versions of windows are not supported anymore. Please let me know if you have any other issues.
